export { default as Abdominals } from './abdominals/index.vue';
export { default as Biceps } from './biceps/index.vue';
export { default as Calves } from './calves/index.vue';
export { default as Chest } from './chest/index.vue';
export { default as Forearms } from './forearms/index.vue';
export { default as Obliques } from './obliques/index.vue';
export { default as Quads } from './quads/index.vue';
export { default as Shoulders } from './shoulders/index.vue';
export { default as Trapeze } from './trapeze/index.vue';
